### Get all jobs
GET http://127.0.0.1:5000/jobs HTTP/1.1
content-type: application/json

### Get single job
GET http://127.0.0.1:5000/jobs/3 HTTP/1.1
content-type: application/json


### Post a job
POST http://127.0.0.1:5000/jobs HTTP/1.1
content-type: application/json

{
    "title": "Software Architecht",
    "description": "Insane offer",
    "salary": 1500000
}

### Publish the job
PUT http://127.0.0.1:5000/jobs/3/publish HTTP/1.1
content-type: application/json

### Update the job
PUT http://127.0.0.1:5000/jobs/2 HTTP/1.1
content-type: application/json

{
    "title": "CEO",
    "description": "GIT GUT",
    "salary": 100000000
}

### DELETE a job
DELETE  http://127.0.0.1:5000/jobs/4 HTTP/1.1
content-type: application/json

### Unpublish a job
DELETE  http://127.0.0.1:5000/jobs/3/publish HTTP/1.1
content-type: application/json