### Get all jobs
GET http://127.0.0.1:5000/jobs HTTP/1.1
content-type: application/json

### Get single job
GET http://127.0.0.1:5000/jobs/2 HTTP/1.1
content-type: application/json


### Post a job
POST http://127.0.0.1:5000/jobs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjk3MjkzMTA5LCJqdGkiOiI4ZGVlOGZkOC1jNGRmLTQ0N2UtOGE5OC03Njg5YWU0MzExODkiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTcyOTMxMDksImV4cCI6MTY5NzI5NDAwOX0.3AYTFnU3GgJDngHRrww90MnzJIeRJ7R9P3tVuNE9vHI

{
    "title": "Full-Stack Developer",
    "description": "Remote Option",
    "salary": 2000000
}

### Publish the job
PUT http://127.0.0.1:5000/jobs/5/publish HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjk3MjkzMTA5LCJqdGkiOiI4ZGVlOGZkOC1jNGRmLTQ0N2UtOGE5OC03Njg5YWU0MzExODkiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTcyOTMxMDksImV4cCI6MTY5NzI5NDAwOX0.3AYTFnU3GgJDngHRrww90MnzJIeRJ7R9P3tVuNE9vHI

### Update the job
PUT http://127.0.0.1:5000/jobs/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjk3MjkzMTA5LCJqdGkiOiI4ZGVlOGZkOC1jNGRmLTQ0N2UtOGE5OC03Njg5YWU0MzExODkiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTcyOTMxMDksImV4cCI6MTY5NzI5NDAwOX0.3AYTFnU3GgJDngHRrww90MnzJIeRJ7R9P3tVuNE9vHI

{
    "title": "CEO",
    "description": "GIT GUT",
    "salary": 100000000
}

### DELETE a job
DELETE  http://127.0.0.1:5000/jobs/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjk3MjkzMTA5LCJqdGkiOiI4ZGVlOGZkOC1jNGRmLTQ0N2UtOGE5OC03Njg5YWU0MzExODkiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTcyOTMxMDksImV4cCI6MTY5NzI5NDAwOX0.3AYTFnU3GgJDngHRrww90MnzJIeRJ7R9P3tVuNE9vHI

### Unpublish a job
DELETE  http://127.0.0.1:5000/jobs/2/publish HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjk3MjkzMTA5LCJqdGkiOiI4ZGVlOGZkOC1jNGRmLTQ0N2UtOGE5OC03Njg5YWU0MzExODkiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTcyOTMxMDksImV4cCI6MTY5NzI5NDAwOX0.3AYTFnU3GgJDngHRrww90MnzJIeRJ7R9P3tVuNE9vHI