### Get all jobs
GET http://127.0.0.1:5000/jobs HTTP/1.1
content-type: application/json

### Get single job
GET http://127.0.0.1:5000/jobs/2 HTTP/1.1
content-type: application/json


### Post a job
POST http://127.0.0.1:5000/jobs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjk3Mjg3OTgzLCJqdGkiOiJlNmY5OGY2Yy1kNzMwLTQ4MjAtYjBiMC00YjI0MTQ2NTUwODUiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoyLCJuYmYiOjE2OTcyODc5ODMsImV4cCI6MTY5NzI4ODg4M30.PbM-TVzd7IqURmsEwW60HOjJurC9z4u_C06HIj5Bjfw

{
    "title": "Full-Stack Developer",
    "description": "Remote Option",
    "salary": 2000000
}

### Publish the job
PUT http://127.0.0.1:5000/jobs/3/publish HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjk3Mjg3OTgzLCJqdGkiOiJlNmY5OGY2Yy1kNzMwLTQ4MjAtYjBiMC00YjI0MTQ2NTUwODUiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoyLCJuYmYiOjE2OTcyODc5ODMsImV4cCI6MTY5NzI4ODg4M30.PbM-TVzd7IqURmsEwW60HOjJurC9z4u_C06HIj5Bjfw


### Update the job
PUT http://127.0.0.1:5000/jobs/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5NzE4OTU2MiwianRpIjoiOGI3Y2ZhMTYtZjY2Yy00OTBkLThiNzgtMDIxN2MwYTI5MWE2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNjk3MTg5NTYyLCJleHAiOjE2OTcxOTA0NjJ9.96krb7zVvl3vO7FwhSe-PIgaLCndAob40fvxGzG5A94


{
    "title": "CEO",
    "description": "GIT GUT",
    "salary": 100000000
}

### DELETE a job
DELETE  http://127.0.0.1:5000/jobs/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5NzE4OTU2MiwianRpIjoiOGI3Y2ZhMTYtZjY2Yy00OTBkLThiNzgtMDIxN2MwYTI5MWE2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNjk3MTg5NTYyLCJleHAiOjE2OTcxOTA0NjJ9.96krb7zVvl3vO7FwhSe-PIgaLCndAob40fvxGzG5A94


### Unpublish a job
DELETE  http://127.0.0.1:5000/jobs/2/publish HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5NzE4OTU2MiwianRpIjoiOGI3Y2ZhMTYtZjY2Yy00OTBkLThiNzgtMDIxN2MwYTI5MWE2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNjk3MTg5NTYyLCJleHAiOjE2OTcxOTA0NjJ9.96krb7zVvl3vO7FwhSe-PIgaLCndAob40fvxGzG5A94
