### Get Access Token
POST http://127.0.0.1:5000/token HTTP/1.1
content-type: application/json

{
    "username": "Leonardo",
    "password": "monaLisa"
}

### Get Refresh Token
POST http://127.0.0.1:5000/refresh HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5NzI5Mjk0NCwianRpIjoiMThlYzQ0MWItOGYyZC00NzlhLTgyYmQtNzVjMjBhN2Q0ZjFlIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOjIsIm5iZiI6MTY5NzI5Mjk0NCwiZXhwIjoxNjk5ODg0OTQ0fQ.rNgr9p5-3aZf2knkHkKIj0MbimpAjd4f8r2unHVvYFs